name: fractal_flame
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dart_numerics: ^0.0.6
  device_info_plus: ^11.1.0
  bitmap: ^0.2.0
  http: ^1.2.2
  image_downloader_web: ^2.0.6
  path_provider: ^2.1.5
  file_picker: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
