name: fractal_flame
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_info_plus: ^11.1.0
  http: ^1.2.2
  path_provider: ^2.1.5
  file_picker: ^8.1.3
#  image_gallery_saver: ^2.0.3
#  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
